
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=mysecretkey
      - DATABASE_URL=postgresql://user:password@db/events_db
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: events_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
